swagger: "2.0"
info:
  version: "0.0.1"
  title: CrowdSauce
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/accounts/:
    x-swagger-router-controller: hello_world
    post:
      description: Create new account
      operationId: create account
      parameters:
        - name: userid
          in: header
          description: UserID for the account to create
          required: true
          type: number
        - name: accesstoken
          in: header
          description: The facebook access token of the user
          required: true
          type: string
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        default:
          description: Error
    delete:
      description: Delete account
      operationId: delete account
      parameters:
        - name: userid
          in: header
          description: UserID for the account to delete
          required: true
          type: number
        - name: accesstoken
          in: header
          description: The facebook access token of the user
          required: true
          type: string
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        default:
          description: Error
      
  /api/posts:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    post:
      description: Create a new post
      operationId: create post
      parameters:
        - name: userid
          in: header
          description: The facebook userId of the user
          required: true
          type: number
        - name: accesstoken
          in: header
          description: The facebook access token of the user
          required: true
          type: string
        - name: body
          in: body
          description: Post data
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        default:
          description: Error
    get:
      description: Returns a list of all the posts of a given user
      operationId: get posts
      parameters:
        - name: userid
          in: header
          description: The facebook userId of the user
          required: true
          type: number
        - name: accesstoken
          in: header
          description: The facebook access token of the user
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Post"
        "401":
          description: Unauthorized
        default:
          description: Error
    put:
      description: Update a post
      operationId: update post
      parameters:
        - name: userid
          in: header
          description: The facebook userId of the user
          required: true
          type: number
        - name: accesstoken
          in: header
          description: The facebook access token of the user
          required: true
          type: string
        - name: postid
          in: query
          description: The post to update
          required: true
          type: string
        - name: body
          in: body
          description: Post data
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        default:
          description: Error
    delete:
      description: Delete posts
      operationId: delete post
      parameters:
        - name: userid
          in: header
          description: The facebook userId of the user
          required: true
          type: string
        - name: accesstoken
          in: header
          description: The facebook access token of the user
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        default:
          description: Error
  /api/posts/feed:
    get:
      description: Get the list of the most recent posts from the given user's friends
      operationId: get feed
      parameters:
      - name: userid
        in: header
        description: The facebook userId of the user
        required: true
        type: string
      - name: accesstoken
        in: header
        description: The facebook access token of the user
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/Feed"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Post"
        "401":
          description: Unauthorized
        default:
          description: Error
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Post:
    properties:
      ingredients:
        type: string
      directions:
        type: string
      recipeLink:
        type: string
      imageLinks:
        type: string
      tags:
        type: array
        items:
          type: string
      notes:
        type: string
      rating:
        type: number
  Feed:
    properties:
      numposts:
        type: number
